all: fifo sjf rr

fifo: fifo/fifo.cpp
	g++ -o fifo fifo/fifo.cpp -Wall -Werror -std=c++20 -g

sjf: sjf/sjf.cpp
	g++ -o sjf sjf/sjf.cpp -Wall -Werror -std=c++20 -g

rr: rr/rr.cpp
	g++ -o rr rr/rr.cpp -Wall -Werror -std=c++20 -g